// <auto-generated />
using System;
using EvilCorp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvilCorp.Migrations
{
    [DbContext(typeof(EvilCorpContext))]
    [Migration("20240630021819_discountsdata")]
    partial class discountsdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvilCorp.Models.AvailableDiscount", b =>
                {
                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("AvailableDiscount");
                });

            modelBuilder.Entity("EvilCorp.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrevClient")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdClient");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("EvilCorp.Models.Company", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Krs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ClientId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("EvilCorp.Models.Discount", b =>
                {
                    b.Property<int>("IdDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiscount"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdDiscount");

                    b.ToTable("Discount");

                    b.HasData(
                        new
                        {
                            IdDiscount = 1,
                            EndDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "March discounts",
                            Name = "Black March",
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3m
                        },
                        new
                        {
                            IdDiscount = 2,
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "June discounts",
                            Name = "June Madness",
                            StartDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.5m
                        },
                        new
                        {
                            IdDiscount = 3,
                            EndDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "For all new customers",
                            Name = "June for noobies",
                            StartDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 5m
                        },
                        new
                        {
                            IdDiscount = 4,
                            EndDate = new DateTime(2024, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Info = "July discounts",
                            Name = "July Madness",
                            StartDate = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3.9m
                        });
                });

            modelBuilder.Entity("EvilCorp.Models.Individual", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ClientId");

                    b.ToTable("Individual");
                });

            modelBuilder.Entity("EvilCorp.Models.Payment", b =>
                {
                    b.Property<int>("IdPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPayment"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("SingleSaleId")
                        .HasColumnType("int");

                    b.HasKey("IdPayment");

                    b.HasIndex("SingleSaleId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("EvilCorp.Models.SingleSale", b =>
                {
                    b.Property<int>("IdSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSale"));

                    b.Property<int>("AdditionalSupportPeriod")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsPaid")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatesInfo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdSale");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SingleSale");
                });

            modelBuilder.Entity("EvilCorp.Models.Software", b =>
                {
                    b.Property<int>("IdSoftware")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSoftware"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("SoftInfo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("VerInfo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdSoftware");

                    b.ToTable("Software");

                    b.HasData(
                        new
                        {
                            IdSoftware = 1,
                            Category = "Digital image processing software",
                            Name = "Lightroom",
                            Price = 5899.99m,
                            SoftInfo = "Image editing software",
                            VerInfo = "Not the latest version",
                            Version = "2023.9.9"
                        },
                        new
                        {
                            IdSoftware = 2,
                            Category = "Digital image processing software",
                            Name = "Lightroom",
                            Price = 5950.00m,
                            SoftInfo = "Image editing software",
                            VerInfo = "Not the latest version",
                            Version = "2024.0.0"
                        },
                        new
                        {
                            IdSoftware = 3,
                            Category = "Digital image processing software",
                            Name = "Lightroom",
                            Price = 5999.99m,
                            SoftInfo = "Image editing software",
                            VerInfo = "Latest version",
                            Version = "2024.1.0"
                        },
                        new
                        {
                            IdSoftware = 4,
                            Category = "Graphic design software",
                            Name = "Photoshop",
                            Price = 5599.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Not the latest version",
                            Version = "2023.8.0"
                        },
                        new
                        {
                            IdSoftware = 5,
                            Category = "Graphic design software",
                            Name = "Photoshop",
                            Price = 5699.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Not the latest version",
                            Version = "2023.9.0"
                        },
                        new
                        {
                            IdSoftware = 6,
                            Category = "Graphic design software",
                            Name = "Photoshop",
                            Price = 5799.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Not the latest version",
                            Version = "2023.9.9"
                        },
                        new
                        {
                            IdSoftware = 7,
                            Category = "Graphic design software",
                            Name = "Photoshop",
                            Price = 5899.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Not the latest version",
                            Version = "2024.0.0"
                        },
                        new
                        {
                            IdSoftware = 8,
                            Category = "Graphic design software",
                            Name = "Photoshop",
                            Price = 6099.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Latest version",
                            Version = "2024.1.1"
                        },
                        new
                        {
                            IdSoftware = 9,
                            Category = "Simple Graphic design software",
                            Name = "Paint 3D PRO",
                            Price = 99.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Latest version",
                            Version = "2022.7.4"
                        },
                        new
                        {
                            IdSoftware = 10,
                            Category = "Graphic design software",
                            Name = "Illustrator",
                            Price = 3999.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Not the latest version",
                            Version = "2024.3.9"
                        },
                        new
                        {
                            IdSoftware = 11,
                            Category = "Simple Graphic design software",
                            Name = "Illustrator",
                            Price = 3999.99m,
                            SoftInfo = "Graphic design software",
                            VerInfo = "Latest version",
                            Version = "2024.4.0"
                        });
                });

            modelBuilder.Entity("EvilCorp.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EvilCorp.Models.AvailableDiscount", b =>
                {
                    b.HasOne("EvilCorp.Models.Discount", "Discount")
                        .WithMany("AvailableDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvilCorp.Models.Software", "Software")
                        .WithMany("AvailableDiscounts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("EvilCorp.Models.Company", b =>
                {
                    b.HasOne("EvilCorp.Models.Client", "Client")
                        .WithOne("Company")
                        .HasForeignKey("EvilCorp.Models.Company", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvilCorp.Models.Individual", b =>
                {
                    b.HasOne("EvilCorp.Models.Client", "Client")
                        .WithOne("Individual")
                        .HasForeignKey("EvilCorp.Models.Individual", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EvilCorp.Models.Payment", b =>
                {
                    b.HasOne("EvilCorp.Models.SingleSale", "SingleSale")
                        .WithMany("Payments")
                        .HasForeignKey("SingleSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SingleSale");
                });

            modelBuilder.Entity("EvilCorp.Models.SingleSale", b =>
                {
                    b.HasOne("EvilCorp.Models.Client", "Client")
                        .WithMany("SingleSales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvilCorp.Models.Software", "Software")
                        .WithMany("SingleSales")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("EvilCorp.Models.Client", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("Individual");

                    b.Navigation("SingleSales");
                });

            modelBuilder.Entity("EvilCorp.Models.Discount", b =>
                {
                    b.Navigation("AvailableDiscounts");
                });

            modelBuilder.Entity("EvilCorp.Models.SingleSale", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EvilCorp.Models.Software", b =>
                {
                    b.Navigation("AvailableDiscounts");

                    b.Navigation("SingleSales");
                });
#pragma warning restore 612, 618
        }
    }
}
